environment: development
server:
  port: 5555
  domain: localhost
  host: http://localhost:5555
database:
  uri: "postgres://postgres:1234@localhost:5432"
  name: shield
secrets:
  signing_key: 87cc20e216861442af1bc993ad6f274b61bb65b956444da50f446b2046c0d260
logger:
  level: debug
admin:
  email: admin@admin.com
  password: 12345
